FatalErrorException: Call to undefined method Illuminate\Support\Facades\Request::all()
There has a conflict between Illuminate\Http\Request and Illuminate\Support\Facades\Request,so it's better to use "Illuminate\Http\Request" replace "Request"